### ISSUE TITLE
Need MaterialPreferenceFragment

### ISSUE THREAD

**Issue by pamtbaau** [AndroidDeveloperLB/MaterialPreferenceLibrary#3]
My app heavily depends on a PreferenceFragment you mention: [https://github.com/kolavar/android-support-v4-preferencefragment](https://github.com/kolavar/android-support-v4-preferencefragment).

You're hinting about using the library with this PreferenceFragment. However, I have no idea how to get that done...

Are you planning to test it yourself and release the steps to combine the two libraries?

**Comment by AndroidDeveloperLB** [comment]
There are 2 possible libraries you can try, and if you don't support pre-Honeycomb versions of Android, I think you don't even need them.
I haven't tested any of them with my library. Maybe in the future. 
But I don't think it's a good idea to merge them. Only put a sample of how it's possible.
I advice to first check if my library fits your needs, as it lacks some stuff (written in the main page).

**Comment by pamtbaau** [comment]
Thanks for your swift response... I do need to support pre-Honeycomb versions of Android. 

Phone:
Your SettingsActivity fits my needs on small devices where I open a SettingsActivity, 

Tablets:
However on tablets I use a SettingsFragment to display settings inline with another fragment. With the inline settingfragment I set display properties (color, font etc.) for the main fragment. For this I'm currently using support-v4-preferencefragment with losts of holo styles for widgets. 
Your MaterialPreferenceLibrary provides a way better look and feel though, and with less effort...

**Comment by AndroidDeveloperLB** [comment]
So it works with the PreferenceFragment ? The official one of the framework? or of one of the libraries?
You could use the PreferenceFragment of the framework for tablets, since official support for them are only from Honeycomb. Just make sure it will only apply for Honeycomb and above...

**Comment by pamtbaau** [comment]
Did some positive testing... 

Used the [https://github.com/kolavar/android-support-v4-preferencefragment](https://github.com/kolavar/android-support-v4-preferencefragment) library to implement a SettingsFragment and created preference definitions using your custom_preference definitions, e.g. 
`<com.lb.material_preferences_library.custom_preferences.ListPreference`
`     ... `
`/>` 

This works beautiful with all of your custom_preferences. Except...

When using your DialogPreference I get the following InvocationException:
`java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at android.support.v4.preference.PreferenceManagerCompat.inflateFromResource(PreferenceManagerCompat.java:148)
            at android.support.v4.preference.PreferenceFragment.addPreferencesFromResource(PreferenceFragment.java:223)
            at com.pamtbaau.settingsactivitydelegate.NodeSettingsFragment.onCreate(NodeSettingsFragment.java:24)
            at android.support.v4.app.Fragment.performCreate(Fragment.java:1766)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:917)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:551)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1129)
            at android.app.Activity.performStart(Activity.java:3791)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1620)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663)
            at android.app.ActivityThread.access$1500(ActivityThread.java:117)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:130)
            at android.app.ActivityThread.main(ActivityThread.java:3683)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class java.lang.reflect.Constructor
            at android.preference.GenericInflater.createItem(GenericInflater.java:397)
            at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:430)
            at android.preference.GenericInflater.rInflate(GenericInflater.java:481)
            at android.preference.GenericInflater.rInflate(GenericInflater.java:493)
            at android.preference.GenericInflater.inflate(GenericInflater.java:326)
            at android.preference.GenericInflater.inflate(GenericInflater.java:263)
            at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:251)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at android.support.v4.preference.PreferenceManagerCompat.inflateFromResource(PreferenceManagerCompat.java:148)
            at android.support.v4.preference.PreferenceFragment.addPreferencesFromResource(PreferenceFragment.java:223)
            at com.pamtbaau.settingsactivitydelegate.NodeSettingsFragment.onCreate(NodeSettingsFragment.java:24)
            at android.support.v4.app.Fragment.performCreate(Fragment.java:1766)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:917)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:551)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1129)
            at android.app.Activity.performStart(Activity.java:3791)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1620)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663)
            at android.app.ActivityThread.access$1500(ActivityThread.java:117)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:130)
            at android.app.ActivityThread.main(ActivityThread.java:3683)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.InstantiationException: com.lb.material_preferences_library.custom_preferences.DialogPreference
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
            at android.preference.GenericInflater.createItem(GenericInflater.java:383)
            at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:430)
            at android.preference.GenericInflater.rInflate(GenericInflater.java:481)
            at android.preference.GenericInflater.rInflate(GenericInflater.java:493)
            at android.preference.GenericInflater.inflate(GenericInflater.java:326)
            at android.preference.GenericInflater.inflate(GenericInflater.java:263)
            at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:251)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at android.support.v4.preference.PreferenceManagerCompat.inflateFromResource(PreferenceManagerCompat.java:148)
            at android.support.v4.preference.PreferenceFragment.addPreferencesFromResource(PreferenceFragment.java:223)
            at com.pamtbaau.settingsactivitydelegate.NodeSettingsFragment.onCreate(NodeSettingsFragment.java:24)
            at android.support.v4.app.Fragment.performCreate(Fragment.java:1766)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:917)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:551)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1129)
            at android.app.Activity.performStart(Activity.java:3791)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1620)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663)
            at android.app.ActivityThread.access$1500(ActivityThread.java:117)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:130)
            at android.app.ActivityThread.main(ActivityThread.java:3683)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
            at dalvik.system.NativeStart.main(Native Method)`

Any idea?

**Comment by AndroidDeveloperLB** [comment]
What do you mean "DialogPreference " ? any of the classes that extend it? or you've tried to put it in XML ?

**Comment by pamtbaau** [comment]
The following is a subset ofthe xml definition for my preferences

    <?xml version="1.0" encoding="utf-8"?>
        <PreferenceScreen
            xmlns:android="http://schemas.android.com/apk/res/android"`
            xmlns:app="http://schemas.android.com/apk/res-auto"`
            android:defaultValue="preferenceDefault"`
            android:title="@string/nodePreferenceScreen_title">
            <PreferenceCategory
               android:summary="preferenceCategoryCloudSummary"
               android:title="@string/cloud_preference_category_title" >
                  <com.lb.material_preferences_library.custom_preferences.EditTextPreference
                      app:dialogTitle="@string/fontSize_preference_dialogTitle"
                      android:key="@string/fontSize_node_preference_key"
                      app:negativeButtonText="@android:string/cancel"
                      android:numeric="integer"
                      android:persistent="false"
                      app:positiveButtonText="@android:string/ok"
                      android:summary="@string/fontSize_preference_summary"
                      android:title="@string/fontSize_preference_title" />
           </PreferenceCategory>
     </PreferenceScreen>

The EditTextPreference is shown in Material style and works ok. 

When adding a DialogPreference I get the InvocationTargetException and a blank preference screen.

    <?xml version="1.0" encoding="utf-8"?>
    <PreferenceScreen xmlns:android="http://schemas.android.com/apk/res/android"
                  xmlns:app="http://schemas.android.com/apk/res-auto"
                  android:defaultValue="preferenceDefault"
                  android:title="@string/nodePreferenceScreen_title">
        <PreferenceCategory
            android:summary="preferenceCategoryCloudSummary"
            android:title="@string/cloud_preference_category_title" >
            <com.lb.material_preferences_library.custom_preferences.EditTextPreference
                app:dialogTitle="@string/fontSize_preference_dialogTitle"
                 android:key="@string/fontSize_node_preference_key"
                 app:negativeButtonText="@android:string/cancel"
                 android:numeric="integer"
                 android:persistent="false"
                 app:positiveButtonText="@android:string/ok"
                 android:summary="@string/fontSize_preference_summary"
                 android:title="@string/fontSize_preference_title" />
             <com.lb.material_preferences_library.custom_preferences.DialogPreference
                 android:key="@string/propagate_node_preference_key"
                 android:persistent="false"
                 app:dialogTitle="@string/propagate_preference_dialogTitle"
                 app:dialogMessage="@string/propagate_preference_dialogMessage"
                 android:title="@string/propagate_preference_title"
                 android:summary="@string/propagate_preference_summary"
                 app:positiveButtonText="@android:string/ok"
                 app:negativeButtonText="@android:string/cancel" />
         </PreferenceCategory>
     </PreferenceScreen>'

**Comment by AndroidDeveloperLB** [comment]
The answer is simple:
You use "DialogPreference", which is defined to be an abstract class (not just in my code, but also in Android's framework).
You should stop using it in the XML file.
If you wish to use something similar you can extend from it instead.

**Comment by pamtbaau** [comment]
Ouch... my bad

In the meantime I've added a custom ConfirmDialogPreference based your DialogPreference which only shows a popup with a title/message. It has an interface which sends which of the Ok/Cancel buttons has been clicked.

Anyways... Your library is a great help to Materialize my Preferences. Thanks for that!

**Comment by AndroidDeveloperLB** [comment]
That's fine. You are welcomed to try out my app and the other repos I've created.
